### ISSUE TITLE
Investigate Omega Craft

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#128]
https://www.curseforge.com/minecraft/mc-mods/omega-craft-mod

**Comment by Zamar037** [comment]
This mod looks neat. I hope it makes it into the modpack.

**Comment by theboo** [comment]
oh... i am blind and didnt see this haha... +1 for this mod... i added  it to 0.4.2 and tried it out in creative a bit, very complete tech mod and has some cool items like short range wireless fluid, item and energy transfer...

kinda weird that it uses its own scripts for recipes instead of just adding CT support, but the scripts seem to be very similar

**Comment by NielsPilgaard** [comment]
While it looks good, it has a few major issues. 
* No datapack support for machines
* No CraftTweaker support for machines
* Nearly no configs
* CurseForge issue tracker
* Closed Source
* All Rights Reserved

All of these things add up to a no.
