### ISSUE TITLE
Game crash when operating a simple Redstone contraption 

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#238]
**Modpack version**
Enigmatica 5 v0.4.7

**Issue**
the game crashes quite often, and I'm not sure if it is something wrong with the installation or a compatibility issue between the mods ..etc. This is a simple redstone setup (button, sticky piston, lectern, villager) It works multiple times, then all of the sudden, the game crashes with this error.

**Logs**
Crash Log attached.
[crash-2020-04-26_06.21.31-client.txt](https://github.com/NillerMedDild/Enigmatica5/files/4535064/crash-2020-04-26_06.21.31-client.txt)
![EnigmaticaCrash#1](https://user-images.githubusercontent.com/64355028/80304131-80069700-87b4-11ea-8647-55a250f7d93a.png)

**Comment by NielsPilgaard** [comment]
Please try updating your java (instructions below) and see if the issue persists :)

You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

<blockquote><div><strong><a href="https://www.java.com/en/download/manual.jsp">Java Downloads for All Operating Systems</a></strong></div><div>Java manual download page. Get the latest version of the Java Runtime Environment (JRE) for Windows, Mac, Solaris, and Linux.</div></blockquote>

**Comment by Ridanisaurus** [comment]
I'm unable to use Twitch as for some odd reason I always have issue with client.jar when starting modded 1.15.2 from Twitch. However, I do a standard forge modded minecraft install, pointing to the Twitch Instance, and that does work. Not sure if I can add the '-version:1.8+' in the JVM Argument, but I did completely uninstall the older version of Java from my machine, and installed the latest one.

I will monitor this error, and see if it occurs again. Thanks for the help.

**Comment by NielsPilgaard** [comment]
Sounds good :)
