### ISSUE TITLE
Random game crash during initialization 

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#239]
**Modpack version**
Enigmatica 5 v0.4.7

**Issue**
When starting Minecraft, sometimes the game works without any issue, while sometimes the game crashes completely during its initialization stage.

**Logs**
Attached.
[crash-2020-04-26_11.57.14-client.txt](https://github.com/NillerMedDild/Enigmatica5/files/4535077/crash-2020-04-26_11.57.14-client.txt)

**Comment by NielsPilgaard** [comment]
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

Please comment again if that does not solve your issue :)

<blockquote><div><strong><a href="https://www.java.com/en/download/manual.jsp">Java Downloads for All Operating Systems</a></strong></div><div>Java manual download page. Get the latest version of the Java Runtime Environment (JRE) for Windows, Mac, Solaris, and Linux.</div></blockquote>
