### ISSUE TITLE
Evaluate Ultra Amplified Dimension

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#24]

**Comment by bessiq** [comment]
I like this mod, especially since there are not many other dimension mods in 1.15 yet. But building the portal was way too easy (andesite, granite, diorite, flint & steel) - especially considering the first time I ever went through there were multiple end city towers around me. Didn't see any end ships, but was easy early game shulker boxes.

Anyway, per my suggestion, the mod author updated it to allow you to configure which blocks are used for the portal. So, if you include this mod you could maybe just make the portal a little more difficult to construct. ;)
