### ISSUE TITLE
The game crashed whilst rendering block entity Error: java.lang.IllegalArgumentException: Cannot use model data for a world other than the current client world

### ISSUE THREAD

**Issue by Ridanisaurus** [NillerMedDild/Enigmatica5#240]
**Modpack version**
Enigmatica 5 v0.4.7

**Issue**
Whenever I'm trying to use the Building Tool from Minecolonies, the game crashes with the attached crash log. Please note that this happens often, but not all the time. I'm using the latest Java as the executable in the launcher.

**Logs**
Attached.
![EnigmaticaCrash#2 2](https://user-images.githubusercontent.com/64355028/80309388-0af78980-87d5-11ea-9af8-fd04463f7e39.png)

![EnigmaticaCrash#2](https://user-images.githubusercontent.com/64355028/80309323-ab00e300-87d4-11ea-9921-74ea1be10492.png)

[crash-2020-04-26_15.38.59-client.txt](https://github.com/NillerMedDild/Enigmatica5/files/4535417/crash-2020-04-26_15.38.59-client.txt)

**Comment by NielsPilgaard** [comment]
I believe this issue will be fixed in both 0.4.8 (pending) and 0.4.9 when I finish that :) 
Updating BotanyPots manually should resolve the issue.

Edit: Could you please let me know if one of those updates fixes the issue, when they're available?
Edit2: I highly encourage that you lower your RAM allocation to at most 8GB, anything above will result in worse performance.

**Comment by Ridanisaurus** [comment]
Thanks for letting me know. I've downgraded the RAM allocation to 8 RAM as suggested.
As for updating Botany, as I'm playing on both a single player, and on a server, I think I will wait until the 0.4.8 is out. Will test it as soon as it is out, and let you know.

**Comment by Ridanisaurus** [comment]
I can confirm that since upgrading to E5 0.4.8, this issue is no longer producible from my side.
