### ISSUE TITLE
Ender Storage

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#336]
https://www.curseforge.com/minecraft/mc-mods/ender-storage-1-8
Also added its dependency CodeChickenLib

**Comment by MuteTiefling** [comment]
Probably a bit late to the party on this one, but if I could make the suggestion... don't include this mod. It directly replaces a feature you've already got present with Nature's Aura with the Ender Crate. The only thing it adds would be over simplified fluid transportation, but that can be done already with a bit of cleverness on the part of the player but sending PNC tanks back and forth.

I fully understand the need for something like an ender chest that can be accessed by automation in a game like minecraft, since chunk loading is costly and long distance transportation isn't otherwise possible without loading every intermediate chunk. But I do feel strongly that we need to allow other mods to shine once in a while to let people discover the possibilities in newer mods.

**Comment by NielsPilgaard** [comment]
I agree for the most part, but yes, a bit late to the party :P
