### ISSUE TITLE
Modular Routers - Missing Recipes

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#344]
**Modpack version**
0.4.13

**Issue**
The following items appear to have no recipes currently

- Security Override Cards
- Breaker Modules
- Extruder Module MK1 (MK2 is fine)

**Logs**
N/A

**Comment by NielsPilgaard** [comment]
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment]
Reported the issue here: https://github.com/desht/ModularRouters/issues/78
thanks!

**Comment by desht** [comment]
Issue is fixed in Modular Routers dev - recipes were in fact registered, just not showing in JEI.  I'll get a new MR release out soon but in the meantime, the following recipes do work in the current version:

* Breaker: Blank Module and any Pickaxe (but use an appropriate pick for the blocks you intend to break)
* Extruder Mk1:  Blank Module, Placer Module & Breaker Module (which is crafted with an appropriate pick, as above)
