### ISSUE TITLE
KubeJS unification: Take 3!

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#399]
```js
tag.stacks.stream().sorted(Comparator.comparing(function(element) {
  var value = modPriorities.indexOf(value);
  return value == -1 ? 2147483647 : value;
})).findFirst();
```
Edit1: `get()` needed at the end

```js
tag.stacks.stream().sorted(Comparator.comparing(function(element) {
  var value = modPriorities.indexOf(value);
  return value == -1 ? 2147483647 : value;
})).findFirst().get();
```

max gave me this snippet on Lat's discord, might do the trick!

**Comment by theboo** [comment]
Oo fancy!!

**Comment by MaxNeedsSnacks** [comment]
Note: If this implementation doesn't work because of `Comparator` not being accessible, you'll need to replace the `function(element)` with a function that accepts two elements and returns an integer based on their relative order in the list, so `1` if `a > b`, `0` if `a == b` and `-1` if `a < b`.

Also just noticed that `Comparator.comparingInt` might be slightly more efficient than `comparing` because it doesn't need to "unbox" the integers afterwards, so that might lead to a small performance improvement
