### ISSUE TITLE
Drawer's Tooltip

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#440]
https://www.curseforge.com/minecraft/mc-mods/drawers-tooltip

**Comment by MuteTiefling** [comment]
Well that seems like an interesting mod for an expert version.

**Comment by Flabort** [comment]
Expert version? It's just a QoL mod, the drawers already keep and store their contents when you pick them up (as I discovered when I was moving mine last week, I expected junk everywhere and instead it was a painless process). This just shows which drawer is which.

**Comment by MuteTiefling** [comment]
> Also, it adds a new ingredient type for modpack devs. It will match only if there is a specific item in the drawer and the amount is greater than a value:

> { "type": "draweringredient:standard", "content": { "tag": "minecraft:coals" }, "amount": 127 }

In other words, you can use filled drawers as crafting components.

**Comment by Flabort** [comment]
Alright, fair enough, didn't see that.

I guess the question is whether it uses up the whole drawer or just the items within and/or the specified amount. 

Now that you point it out, I definitely see how that would be useful for an expert type mod pack - I can even think of how to automate a recipe using X items within a drawer making use of a block breaker and block placer. I don't really see that feature being used in the regular version of the pack, though.

**Comment by MuteTiefling** [comment]
Yeah, it'd be a bit much to implement for a regular kitchen sink pack. But it could be used as a nice challenge for automation in an expert pack. Lots of ways to do it. Probably the simplest being an AE2 sub network that takes all the items meant for the drawer, places the drawer, exports the item, and imports it. No need for any other mods. Could be easily done with PNC drones too. 

Without testing, I'd assume the drawer is not consumed, since it can potentially have more than is required for the craft. I'd expect it to just extract the contents like fluid crafting does with a tank. But... that might be expecting a bit much. If it does consume the drawer, however, that shouldn't be an issue unless drawers are made very expensive. Just a bit of wood. Nothing too terrible to automate.
