### ISSUE TITLE
Remove Everlasting Abilities

### ISSUE THREAD

**Issue by NielsPilgaard** [NillerMedDild/Enigmatica5#449]
I've grown to regret adding this, as it's a bit OP from the start, and potentially a lot of clutter.

**Comment by MuteTiefling** [comment]
I can't die right now because of it. I set up an apotheosis spawner and ended up getting so many of these that I've got every useful ability after about half an hour of 'effort'.

I can't drown, don't burn, never have to eat unless I vein mine too much... absorption hearts for days...

Totally agree with removing.

**Comment by Darkere** [comment]
It could be a nice random lategame reward I think. 

Just dropping from mobs though is pretty OP. Could potentially be limited by introducing some form of limitation on how many of them you can have active at a time.

**Comment by MuteTiefling** [comment]
The thing is, even if they're rewards from something... most of the things it gives can be found through more more interesting means in the pack. Late game, you likely already have access to anything it could provide. Early game, it's majorly powerful. Both my e5 games happened to start off with me getting a free Fire Resist ability... that was huge early game and made the nether accessible way earlier than it might have been otherwise.
