### ISSUE TITLE
Botania Flower Pouch is crashing

### ISSUE THREAD

**Issue by ManiacRobertWasTaken** [NillerMedDild/Enigmatica5#512]
**Modpack version**
0.6.0

**Issue**
When i open flower pouch, it's crashing.

**Logs**
https://pastebin.com/uV9DY5Ci

**Comment by NielsPilgaard** [comment]
Thanks for the report, will look into it. A thing to try:

You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

<blockquote><div><strong><a href="https://www.java.com/en/download/manual.jsp">Java Downloads for All Operating Systems</a></strong></div><div>Java manual download page. Get the latest version of the Java Runtime Environment (JRE) for Windows, Mac, Solaris, and Linux.</div></blockquote>

**Comment by ManiacRobertWasTaken** [comment]
Crash was fixed with argument && java update
