### ISSUE TITLE
Crash with PNC item filtering

### ISSUE THREAD

**Issue by MuteTiefling** [NillerMedDild/Enigmatica5#526]
**Modpack version**
0.6.3

**Issue**
While programming drones in PNC, you have the option of either searching for items from all items in the game or picking from your inventory. Doing the former results in this crash. Picking from inventory works as expected. 

**Logs**
https://gist.github.com/MuteTiefling/fd7cc245ec674e0431367f8b10309d40

**Comment by desht** [comment]
This crash is in the `Item#addInformation()` method - some item's implementation of this is crashing.  The item searcher gui calls this method, since it searches on the text added by this method.  So the crash is not in PNC itself, but in which item it's trying to get the text for.

I can add a workaround (catch and ignore any NPE from calling this) but obviously this doesn't fix the root cause...

**Comment by Darkere** [comment]
Ah then this might be related to the PVJ crash. One of their items tooltip is crashing.

**Comment by NielsPilgaard** [comment]
As Darkere pointed out this is most likely caused by this issue: https://github.com/OrderedChaos-Dev/ProjectVibrantJourneys/issues/113
